export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const ORDER_STATUSES_ARRAY = Object.values(ORDER_STATUSES);

/**
 * Valid transitions: key = current status, value = array of allowed next statuses
 */
export const VALID_TRANSITIONS = {
  [ORDER_STATUSES.PENDING]: [
    ORDER_STATUSES.ACCEPTED,
    ORDER_STATUSES.REJECTED,
    ORDER_STATUSES.CANCELLED,
  ],
  [ORDER_STATUSES.ACCEPTED]: [ORDER_STATUSES.OUT_FOR_DELIVERY],
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.DELIVERED],
  [ORDER_STATUSES.DELIVERED]: [ORDER_STATUSES.COMPLETED],
  [ORDER_STATUSES.COMPLETED]: [],
  [ORDER_STATUSES.REJECTED]: [],
  [ORDER_STATUSES.CANCELLED]: [],
};

export const NOTIFICATION_TYPES = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  LOW_STOCK: 'LOW_STOCK',
  WEATHER_ALERT: 'WEATHER_ALERT',
  MARKET_ALERT: 'MARKET_ALERT',
  CROP_ALERT: 'CROP_ALERT',
  ADMIN_RESPONSE: 'ADMIN_RESPONSE',
};

export const NOTIFICATION_TYPES_ARRAY = Object.values(NOTIFICATION_TYPES);
