export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  FINAL: 'FINAL',
  REJECTED: 'REJECTED',
  CHANGES_REQUESTED: 'CHANGES_REQUESTED',
};

export const TRANSACTION_STATUS_ARRAY = Object.values(TRANSACTION_STATUS);
